# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # BOX_VERSION: "20190608.01"
  DOCKER_COMMAND: docker
  PACKER_IMAGES_OUTPUT_DIR: /var/tmp/packer-templates-images
  LOGDIR: /var/tmp/packer-templates-logs
  VAGRANTUP_USER: peru
  PACKER_RUN_TIMEOUT: 18000
  USE_DOCKERIZED_PACKER: "false"
  # PACKER_LOG: 1
  # VAGRANT_LOG: info

before_script:
  - export BOX_VERSION=${BOX_VERSION:-$(date +%Y%m%d).01}
  - test -d /home/gitlab-runner/packer_cache || mkdir -v /home/gitlab-runner/packer_cache
  - ln -sv /home/gitlab-runner/packer_cache packer_cache
  - echo "*** ${BOX_VERSION} | $(date)"

after_script:
  - rm packer_cache
  - date

.job_template: &job_definition
  script:
    - ./build.sh ${CI_JOB_NAME}
    - ./vagrant_init_destroy_boxes.sh ${PACKER_IMAGES_OUTPUT_DIR}/${CI_JOB_NAME}.box
    - ./upload_box_to_vagrantup.sh ${VAGRANTUP_USER}@${PACKER_IMAGES_OUTPUT_DIR}/${CI_JOB_NAME}.box
    - rm -v ${PACKER_IMAGES_OUTPUT_DIR}/${CI_JOB_NAME}.box
  tags:
    - packer-templates
  retry: 1
  # Run only when triggered by Web GUI or scheduled by GitLab
  only:
    - schedules
    - web

stages:
  - ubuntu-18.04-server-amd64-libvirt
  - ubuntu-18.04-server-amd64-virtualbox
  - ubuntu-18.04-desktop-amd64-libvirt
  - ubuntu-18.04-desktop-amd64-virtualbox

ubuntu-18.04-server-amd64-libvirt:
  stage: ubuntu-18.04-server-amd64-libvirt
  <<: *job_definition

ubuntu-18.04-server-amd64-virtualbox:
  stage: ubuntu-18.04-server-amd64-virtualbox
  <<: *job_definition

ubuntu-18.04-desktop-amd64-libvirt:
 stage: ubuntu-18.04-desktop-amd64-libvirt
 <<: *job_definition

ubuntu-18.04-desktop-amd64-virtualbox:
 stage: ubuntu-18.04-desktop-amd64-virtualbox
 <<: *job_definition

check_accessibility_vagrant_cloud:
  stage: check_accessibility_vagrant_cloud
  when: always
  tags:
    - packer-templates
  script:
    - for NAME in ubuntu-{18.04}-desktop-amd64 ubuntu-{18.04}-server-amd64; do
        for VAGRANT_PROVIDER in virtualbox libvirt; do
          CURRENT_VERSION=$(curl -s https://app.vagrantup.com/api/v1/box/peru/$NAME | jq -r ".current_version.version") ;
          URL="https://app.vagrantup.com/peru/boxes/$NAME/versions/$CURRENT_VERSION/providers/$VAGRANT_PROVIDER.box" ;
          echo "*** $URL" ;
          curl -L --fail --silent --head --output /dev/null "$URL" || ( echo "* Failed... ^^^" && exit 1 )
        done
      done
