blank_issues_enabled: false
contact_links:
  - name: GitHub Actions Community Forum
    url: https://github.com/orgs/community/discussions/
    about: Please ask questions about GitHub Actions here.
  - name: GitHub Pages help
    url: https://help.github.com/en/github/working-with-github-pages
    about: GitHub Pages documentation here.
