name: ansible-lint

on:
  push:
    branches-ignore:
      - main
    paths:
      - ansible/**
      - .github/workflows/ansible-lint.yml

jobs:
  ansible-playbooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@v6.0.2
        with:
          targets: ansible/*.yml
          args: -x role-name
