name: dependabot-auto-merge

on:
  pull_request_target:

jobs:
  auto-merge:
    name: Auto approve pull request, then squash and merge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN_FOR_GITHUB_ACTIONS }}
