---
name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@31c86eb3b33c9b601a1f60f98dcbfd1d70f379b4 # v1.10.3
        id: app-token
        with:
          app-id: ${{ secrets.MY_RENOVATE_GITHUB_APP_ID }}
          private-key: ${{ secrets.MY_RENOVATE_GITHUB_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@e4dc86ba9405554aeba3c6bb2d169500e7d3b4ee # v4.1.1
        with:
          release-type: simple
          token: ${{ steps.app-token.outputs.token }}
